{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  app-secret: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "app-secret" "providedValues" (list "kimaiAppSecret") "context" $) }}
  admin-password: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "admin-password" "providedValues" (list "kimaiAdminPassword") "context" $) }}
  mailer-url: {{ .Values.kimaiMailerUrl | b64enc | quote }}
  database-url: {{ include "kimai.databaseUrl" . | b64enc | quote }}
{{- end -}}
